### ISSUE TITLE
Note on "Creating a Function"

### ISSUE THREAD

**Issue by Emmavt** [dlab-berkeley/Python-Intermediate#15]
If the instructor wants to demonstrate why quotation marks are needed around "0-99% FPL", if they use type(df['poverty_level'][0]), they'll get a Pandas Series, as the indices are repeated due to the pd.concat used to create df. It might be worth discussing df indices, or resetting the indices when creating df in the first place.

**Comment by tomvannuenen** [comment]
@Emmavt
